- org.openrewrite.yaml.MergeYaml:
    key: $.spring.threads.virtual
    yaml: |
      enabled: true
    filePattern: "**/application.yml"
- org.openrewrite.yaml.MergeYaml:
    key: $.management.endpoints.web.exposure
    yaml: |
      include: health,info,metrics,prometheus
    filePattern: "**/application.yml"
- org.openrewrite.yaml.MergeYaml:
    key: $.management.tracing.sampling
    yaml: |
      probability: 1.0
    filePattern: "**/application.yml"
- org.openrewrite.yaml.MergeYaml:
    key: $.logging.pattern.level
    yaml: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-},%X{userId:-}]"
    filePattern: "**/application.yml"
