- org.openrewrite.yaml.MergeYaml:
    key: $.jwt
    yaml: |
      jwk-set-uri: "{{jwt_jwk_set_uri}}"
      issuer: jloom-app
      audience: "{{jwt_audience}}"
      cors:
        allowed-origins: "{{cors_allowed_origins}}"
    filePattern: "**/application.yml"
