- org.openrewrite.yaml.MergeYaml:
    key: $.spring
    yaml: |
      data:
        redis:
          host: localhost
          port: 6379
          password: ""
          timeout: 2s
          connect-timeout: 2s
      cache:
        redis:
          time-to-live: 10m
    filePattern: "**/application.yml"
