- org.openrewrite.yaml.MergeYaml:
    key: $.spring
    yaml: |
      cache:
        caffeine:
          spec: "maximumSize=500,expireAfterWrite=600s,recordStats"
    filePattern: "**/application.yml"
