- org.openrewrite.yaml.MergeYaml:
    key: $.management
    yaml: |
      tracing:
        sampling:
          probability: 1.0
      endpoints:
        web:
          exposure:
            include: health,info,metrics,prometheus
    filePattern: "**/application.yml"
